using System;
using System.Collections.Generic;
using System.Data;
using System.Text;
using System.Windows.Forms;
using Oracle.ManagedDataAccess.Client;



namespace ClassExports
{
    /// <summary>
    /// Autor:      Artur Bałon
    /// Changelog: 
    /// Created     01-2024
    /// Description:Szybkie gemerowanie skryptu do exportu damych 
    /// </summary>
    /// 
    public class ClassExports
    {

        private string GenExportScript(Oracle.ManagedDataAccess.Client.OracleConnection OraConn, string OraDir, List<string> OraUsers)
        {

            string sqlString = "select directory_name || '(' || directory_path || ')'\n" +
                                 "  from dba_directories\n" +
                                 " order by directory_name";

            List<string> dirlist = new List<string>();
            OracleCommand cmd = new OracleCommand(sqlString, OraConn);
            OracleDataReader reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                dirlist.Add(reader.GetValue(0).ToString().ToUpper());
            }

            if (OraDir != null)
            {
                List<string> users = new List<string>();

                foreach (string usr in OraUsers)
                {
                    users.Add(usr);
                }

                return ExpdpScript(OraDir, users.ToArray(), OraConn);
            }
            return null;
        }

        public string ExpdpScript(string dir, string[] users, Oracle.ManagedDataAccess.Client.OracleConnection OraConn)
        {
            if (dir != null)
            {
                string schemas = string.Empty;
                string script = string.Empty;

                schemas = String.Join(",", users);

                script += "Generated by AssecoTools Sotfare";
                script += "Check this script carefully";

                script += "DIRECTORY=" + dir.Substring(0, dir.LastIndexOf("(")) + "\n";

                script += "DUMPFILE=asstoo_" + String.Format("{0:yyyy_mm_dd_HHmmss}", DateTime.Now) + "_%U.dp" + "\n";
                script += "LOGFILE=asstoo_" + String.Format("{0:yyyy_mm_dd_HHmmss}", DateTime.Now) + ".log" + "\n";
                script += "\n";
                script += "SCHEMAS=" + schemas + "\n";
                script += "\n";
                script += "PARALLEL=4\n";
                script += "\n";

                string sqlString2 = "SELECT to_char(DBMS_FLASHBACK.GET_SYSTEM_CHANGE_NUMBER) from dual";
                OracleCommand cmd2 = new OracleCommand(sqlString2, OraConn);
                string flashback = cmd2.ExecuteScalar().ToString();
                script += "FLASHBACK_TIME=SYSDATE\n";
                script += "#Additional SCN";
                script += "#SELECT to_char(DBMS_FLASHBACK.GET_SYSTEM_CHANGE_NUMBER) from dual\n";
                script += "#FLASHBACK_SCN=" + flashback + "\n";
                script += "\n";

                List<string> tablespaces = GetUserUsedTablespaces(users, OraConn);

                script += "\n";
                script += "#impdp options\n";
                script += "\n";
                if (tablespaces != null)
                {
                    script += "Check tablespaces. If true then uncomment";
                    script += "#REMAP_TABLESPACE=" + String.Join(":,", tablespaces.ToArray()) + ":\n";
                }
                script += "\n";
                script += "TRANSFORM=OID:N" + "\n";
                script += "#TRANSFORM=SEGMENT_ATTRIBUTES:N" + "\n";

                return script;


            }
            return null;
        }
        public List<string> GetUserUsedTablespaces(string[] owners, Oracle.ManagedDataAccess.Client.OracleConnection OraConn)
        {
            try
            {
                string ownerList = "'" + String.Join("','", owners) + "'";
                OracleCommand cmd = new OracleCommand("select distinct(tablespace_name)  from dba_segments where OWNER IN (" + ownerList + ") union select distinct(tablespace_name) from dba_tab_partitions where table_owner in (" + ownerList + ")", OraConn);
                OracleDataReader reader = cmd.ExecuteReader();

                List<string> tablespaces = new List<string>();
                while (reader.Read())
                {
                    tablespaces.Add(reader.GetValue(0).ToString());
                }
                return tablespaces;
            }
            catch (OracleException ex)
            { 
                return null; 
            }

        }
    }

}
