//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssecoTools.Lang {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangRes() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssecoTools.Lang.LangRes", typeof(LangRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu About.
        /// </summary>
        internal static string Form1_aboutToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("Form1_aboutToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu BytesSend.
        /// </summary>
        internal static string Form1_btnBytesSend_Text {
            get {
                return ResourceManager.GetString("Form1_btnBytesSend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Commits.
        /// </summary>
        internal static string Form1_btnCommits_Text {
            get {
                return ResourceManager.GetString("Form1_btnCommits_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu CPU.
        /// </summary>
        internal static string Form1_btnCPUBYTHIS_Text {
            get {
                return ResourceManager.GetString("Form1_btnCPUBYTHIS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DDL.
        /// </summary>
        internal static string Form1_btnDDL_Text {
            get {
                return ResourceManager.GetString("Form1_btnDDL_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Daedlocks.
        /// </summary>
        internal static string Form1_btnDeadlocks_Text {
            get {
                return ResourceManager.GetString("Form1_btnDeadlocks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Executes.
        /// </summary>
        internal static string Form1_btnExecutes_Text {
            get {
                return ResourceManager.GetString("Form1_btnExecutes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gain.
        /// </summary>
        internal static string Form1_btnGain_Text {
            get {
                return ResourceManager.GetString("Form1_btnGain_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lockersy.
        /// </summary>
        internal static string Form1_btnHolds_Text {
            get {
                return ResourceManager.GetString("Form1_btnHolds_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In trnaslate ;).
        /// </summary>
        internal static string Form1_btnHolds_ToolTip {
            get {
                return ResourceManager.GetString("Form1_btnHolds_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Locks.
        /// </summary>
        internal static string Form1_btnLocks_Text {
            get {
                return ResourceManager.GetString("Form1_btnLocks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show locks with history.
        /// </summary>
        internal static string Form1_btnLocks_ToolTip {
            get {
                return ResourceManager.GetString("Form1_btnLocks_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu LongOps.
        /// </summary>
        internal static string Form1_btnLongOps_Text {
            get {
                return ResourceManager.GetString("Form1_btnLongOps_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Parses.
        /// </summary>
        internal static string Form1_btnParses_Text {
            get {
                return ResourceManager.GetString("Form1_btnParses_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu PhysReads.
        /// </summary>
        internal static string Form1_btnPhysicalReads_Text {
            get {
                return ResourceManager.GetString("Form1_btnPhysicalReads_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error.
        /// </summary>
        internal static string Form1_btnSerwerror_Text {
            get {
                return ResourceManager.GetString("Form1_btnSerwerror_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sessions.
        /// </summary>
        internal static string Form1_btnSessions_Text {
            get {
                return ResourceManager.GetString("Form1_btnSessions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stats.
        /// </summary>
        internal static string Form1_btnTableStatistics_Text {
            get {
                return ResourceManager.GetString("Form1_btnTableStatistics_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stats check/run.
        /// </summary>
        internal static string Form1_btnTableStatistics_ToolTip {
            get {
                return ResourceManager.GetString("Form1_btnTableStatistics_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Active Transaction.
        /// </summary>
        internal static string Form1_btnTrans_Text {
            get {
                return ResourceManager.GetString("Form1_btnTrans_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Active Transaction.
        /// </summary>
        internal static string Form1_btnTrans_ToolTip {
            get {
                return ResourceManager.GetString("Form1_btnTrans_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User Calls.
        /// </summary>
        internal static string Form1_btnUserCalls_Text {
            get {
                return ResourceManager.GetString("Form1_btnUserCalls_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Global UNDO Summary.
        /// </summary>
        internal static string Form1_button_GlobalUndo_Text {
            get {
                return ResourceManager.GetString("Form1_button_GlobalUndo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Connect.
        /// </summary>
        internal static string Form1_connectToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("Form1_connectToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Disconnect.
        /// </summary>
        internal static string Form1_disconnectToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("Form1_disconnectToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu EN.
        /// </summary>
        internal static string Form1_eNToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("Form1_eNToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File.
        /// </summary>
        internal static string Form1_fileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("Form1_fileToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Database Connection .
        /// </summary>
        internal static string Form1_fileToolStripMenuItem_ToolTip {
            get {
                return ResourceManager.GetString("Form1_fileToolStripMenuItem_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Schemas.
        /// </summary>
        internal static string Form1_FormSchemaStats_tabPage1_Text {
            get {
                return ResourceManager.GetString("Form1_FormSchemaStats_tabPage1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sessions.
        /// </summary>
        internal static string Form1_groupBox1_Text {
            get {
                return ResourceManager.GetString("Form1_groupBox1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Monitor buttons ( work work work.... ).
        /// </summary>
        internal static string Form1_groupBox2_Text {
            get {
                return ResourceManager.GetString("Form1_groupBox2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Developper.
        /// </summary>
        internal static string Form1_groupBox3_Text {
            get {
                return ResourceManager.GetString("Form1_groupBox3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Info.
        /// </summary>
        internal static string Form1_infoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("Form1_infoToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lang.
        /// </summary>
        internal static string Form1_langToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("Form1_langToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Options.
        /// </summary>
        internal static string Form1_optionsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("Form1_optionsToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu PL.
        /// </summary>
        internal static string Form1_pLToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("Form1_pLToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu CheckStatistics.
        /// </summary>
        internal static string FormSchemaStats_checkStatisticsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_checkStatisticsToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create 3 Scripts(table level).
        /// </summary>
        internal static string FormSchemaStats_createScriptToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_createScriptToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DetailErrorLog.
        /// </summary>
        internal static string FormSchemaStats_errorToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_errorToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GatherStatistics.
        /// </summary>
        internal static string FormSchemaStats_gatherStatisticsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_gatherStatisticsToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Found rows are....
        /// </summary>
        internal static string FormSchemaStats_GridInfo {
            get {
                return ResourceManager.GetString("FormSchemaStats_GridInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SelectSchemas.
        /// </summary>
        internal static string FormSchemaStats_groupBox1_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_groupBox1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Progres.
        /// </summary>
        internal static string FormSchemaStats_groupBox2_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_groupBox2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Object.
        /// </summary>
        internal static string FormSchemaStats_label1_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_label1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Done.
        /// </summary>
        internal static string FormSchemaStats_label1_Worker_Done {
            get {
                return ResourceManager.GetString("FormSchemaStats_label1_Worker_Done", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wait... .
        /// </summary>
        internal static string FormSchemaStats_label1_Worker_DoWork {
            get {
                return ResourceManager.GetString("FormSchemaStats_label1_Worker_DoWork", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wait stored procedure is running ....
        /// </summary>
        internal static string FormSchemaStats_label1_Worker_DoWork_StoredProc {
            get {
                return ResourceManager.GetString("FormSchemaStats_label1_Worker_DoWork_StoredProc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Found some recomendations.
        /// </summary>
        internal static string FormSchemaStats_label1_Worker_FoundRcommendations {
            get {
                return ResourceManager.GetString("FormSchemaStats_label1_Worker_FoundRcommendations", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Errors/Warnings.
        /// </summary>
        internal static string FormSchemaStats_label3_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_label3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Parallel.
        /// </summary>
        internal static string FormSchemaStats_label4_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_label4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu EstimatePercent.
        /// </summary>
        internal static string FormSchemaStats_label5_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_label5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Modiff.
        /// </summary>
        internal static string FormSchemaStats_label6_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_label6_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string FormSchemaStats_labelObject_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_labelObject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu LockSchema.
        /// </summary>
        internal static string FormSchemaStats_lockSchemaToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_lockSchemaToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu RunLog.
        /// </summary>
        internal static string FormSchemaStats_logToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_logToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Refresh.
        /// </summary>
        internal static string FormSchemaStats_refreshToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_refreshToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Script copied to clipboard.
        /// </summary>
        internal static string FormSchemaStats_ScriptCopied {
            get {
                return ResourceManager.GetString("FormSchemaStats_ScriptCopied", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ShowTableStats.
        /// </summary>
        internal static string FormSchemaStats_showStatTablesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_showStatTablesToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tables.
        /// </summary>
        internal static string FormSchemaStats_tablesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_tablesToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Schemas.
        /// </summary>
        internal static string FormSchemaStats_tabPage1_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_tabPage1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu StatisticsOptions.
        /// </summary>
        internal static string FormSchemaStats_tabPage2_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_tabPage2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create script .
        /// </summary>
        internal static string FormSchemaStats_tbtnCreateScript_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_tbtnCreateScript_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stop.
        /// </summary>
        internal static string FormSchemaStats_tbtnStop_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_tbtnStop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ALL.
        /// </summary>
        internal static string FormSchemaStats_toolStripButton1_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_toolStripButton1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu PRC.
        /// </summary>
        internal static string FormSchemaStats_toolStripButton2_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_toolStripButton2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GatherStats.
        /// </summary>
        internal static string FormSchemaStats_toolStripButton3_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_toolStripButton3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu COUNT.
        /// </summary>
        internal static string FormSchemaStats_toolStripButton4_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_toolStripButton4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu MOD.
        /// </summary>
        internal static string FormSchemaStats_toolStripButton5_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_toolStripButton5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu MISS.
        /// </summary>
        internal static string FormSchemaStats_toolStripButton6_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_toolStripButton6_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu COLS.
        /// </summary>
        internal static string FormSchemaStats_toolStripButton7_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_toolStripButton7_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Logs.
        /// </summary>
        internal static string FormSchemaStats_toolStripDropDownButton1_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_toolStripDropDownButton1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu UnlockSchema.
        /// </summary>
        internal static string FormSchemaStats_unlockSchemaToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("FormSchemaStats_unlockSchemaToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tables.
        /// </summary>
        internal static string FormTableStats_TabPage1_Text {
            get {
                return ResourceManager.GetString("FormTableStats_TabPage1_Text", resourceCulture);
            }
        }
    }
}
